### ISSUE TITLE
protobuf version is too low

### ISSUE THREAD

**Issue by danyang-rainbow** [THUDM/icetk#10]
Could you please upgrade base protobuf version? Thanks!

I have problem integrating this tool into huggingface datasets.

**Comment by physercoe** [comment]
similar problems too, please upgrade the base protobuf version, thanks

**Comment by bash99** [comment]
protobuf <3.19 (3.18.3) is still too low, it still suffer a bug in below link

https://github.com/protocolbuffers/protobuf/issues/10075

when can be reproduced with (code from above link)
```
# test.py
from google.protobuf import descriptor_pool as _descriptor_pool

desc1 = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"\x03\n\x01M')
desc2 = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"\x03\n\x01M')

print(desc1)
print(desc2)

assert desc1 is not None
assert desc2 is not None
assert desc1 is desc2
```

When I can test with https://github.com/yuanzhoulvpi2017/zero_nlp/tree/main/Chatglm6b_ModelParallel I got that bug
"[AttributeError: 'NoneType' object has no attribute 'message_types_by_name']"
#8 

I've try use protobuf 3.20.3 (by pip install "protobuf<4" ), it seems ok.
