### ISSUE TITLE
How did the tokenizer learned?

### ISSUE THREAD

**Issue by silverriver** [THUDM/icetk#4]
Could you provide more details about how these tokenizers are learned?

for example:
1. On what images/texts did the vqvae/sentencepiece tokenizers learned
2. For the text tokenizer, how to learn two vocab? Did you learn the Chinese and English vocab respectively and try to merge them? Does the sentencepiece lib provide such a feature?
3. Which mode did you use to build sentencepiece tokenizer? unigram or bpe or wordpiece?
4. Have you consider to use byte-level bpe (as GPT2) since it can handle almost all unicode tokens.

**Comment by Sleepychord** [comment]
1. The image embeddings are learned on CogView dataset, and the text tokenizer is learned on a subset of pile and wudaocorpus. 
2. We separately train the two dictionary and merge them by some processing to prevent repetition. Jointly training will result in unbalance in our experiments. We use sentencepiece from google.
3. unigram
4. Unfortunately no.

**Comment by silverriver** [comment]
Thank you for your quick response.
I have some followup questions regarding to the process used in merging the Chinese and English vocab.
1. How do you merge these vocab after removing the repetition? Did the sentencepiece lib provide such api? or you directly modify the internal state of the spm model?
2. How to estimate the probability associated with each token when merging the vocab.

thank you very much in advance

**Comment by Sleepychord** [comment]
1. No, they don't have this api. I manually modify the internal state.
2. Just make the Chinese and English tokens basically equal, which is what we want.

**Comment by silverriver** [comment]
I am wondering if it possible for you to share the script used to merge these vocabs?

**Comment by Sleepychord** [comment]
I am sorry, they are mostly ipython on-the-fly and I didn't saved them.

**Comment by silverriver** [comment]
Thank you for your replay
